[package]
name = "com"
version = "1.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true